### ISSUE TITLE
OSError: cannot load library 'gobject-2.0-0': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'gobject-2.0-0'

### ISSUE THREAD

**Issue by WcombL** [robertzhangwenjie/gitbook2pdf#6]
(venv) PS D:\coursera-dl\gitbook2pdf> python gitbook.py https://joshhug.gitbooks.io/hug61b/content/ cs61b.pdf
Traceback (most recent call last):
  File "D:\coursera-dl\gitbook2pdf\gitbook.py", line 2, in <module>
    from gitbook2pdf import Gitbook2PDF
  File "D:\coursera-dl\gitbook2pdf\gitbook2pdf\__init__.py", line 1, in <module>
    from .gitbook2pdf import Gitbook2PDF
    gobject = _dlopen(
  File "D:\coursera-dl\gitbook2pdf\venv\lib\site-packages\weasyprint\text\ffi.py", line 390, in _dlopen
    return ffi.dlopen(names[0])  # pragma: no cover
  File "D:\coursera-dl\gitbook2pdf\venv\lib\site-packages\cffi\api.py", line 150, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "D:\coursera-dl\gitbook2pdf\venv\lib\site-packages\cffi\api.py", line 832, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "D:\coursera-dl\gitbook2pdf\venv\lib\site-packages\cffi\api.py", line 827, in _load_backend_lib
    raise OSError(msg)
OSError: cannot load library 'gobject-2.0-0': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'gobject-2.0-0'
(venv) PS D:\coursera-dl\gitbook2pdf> python --version
Python 3.10.7
(venv) PS D:\coursera-dl\gitbook2pdf>

**Comment by midpoint** [comment]
Try it again under Python 3.9
